services:
  - type: web
    name: famy-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        sync: false
      - key: PORT
        generateValue: false
        value: 3000
